package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 * The view class of the login feature.
 * 
 * This class is instantiated with a LoginController and LoginModel object, from which it 
 * receives information to draw to the screen.
 * 
 * An instance of this class is created by the Driver when the program is run.
 * 
 * @author Bryan
 */
public class LoginView extends javax.swing.JFrame {

    /**
     * Constructor for LoginView()
     */
    public LoginView() {
        initComponents(); // initialise JFrame objects from Netbeans GUI Builder
        this.setVisible(true);
    }
 
   /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        window = new javax.swing.JPanel();
        loginTitleLabel = new javax.swing.JLabel();
        idTextfield = new javax.swing.JTextField();
        idLabel = new javax.swing.JLabel();
        idSubmitBtn = new javax.swing.JButton();
        errorMsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(20, 40, 50));

        window.setBackground(new java.awt.Color(52, 78, 92));

        loginTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        loginTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginTitleLabel.setText("LOGIN");
        loginTitleLabel.setAlignmentY(0.0F);

        idLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        idLabel.setForeground(new java.awt.Color(255, 255, 255));
        idLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idLabel.setText("Practitioner ID:");
        idLabel.setAlignmentY(0.0F);

        idSubmitBtn.setText("GO");

        errorMsg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        errorMsg.setForeground(new java.awt.Color(239, 61, 89));

        javax.swing.GroupLayout windowLayout = new javax.swing.GroupLayout(window);
        window.setLayout(windowLayout);
        windowLayout.setHorizontalGroup(
            windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(windowLayout.createSequentialGroup()
                .addGroup(windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(windowLayout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(loginTitleLabel))
                    .addGroup(windowLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idLabel)
                            .addGroup(windowLayout.createSequentialGroup()
                                .addComponent(idTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(idSubmitBtn))
                            .addComponent(errorMsg))))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        windowLayout.setVerticalGroup(
            windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(windowLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(loginTitleLabel)
                .addGap(50, 50, 50)
                .addComponent(idLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idSubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorMsg)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(window, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(window, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Gets ID text field.
     * @return JTextField
     */
    public JTextField getIdTextfield() {
        return idTextfield;
    }
    
    /**
     * Gets ID login submit button.
     * @return JButton
     */
    public JButton getIdSubmitBtn() {
        return idSubmitBtn;
    }
    
    /**
     * Gets error message label component.
     * @return JLabel
     */
    public JLabel getErrorMsg() {
        return errorMsg;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorMsg;
    private javax.swing.JLabel idLabel;
    private javax.swing.JButton idSubmitBtn;
    private javax.swing.JTextField idTextfield;
    private javax.swing.JLabel loginTitleLabel;
    private javax.swing.JPanel window;
    // End of variables declaration//GEN-END:variables
}
